# Generated by Django 5.2.7 on 2025-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
