# Generated by Django 5.2.7 on 2025-11-10 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0003_alter_echo_updated_at_alter_echo_user'),
        ('waves', '0002_alter_wave_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='echo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='echos.echo'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to=settings.AUTH_USER_MODEL),
        ),
    ]
