# Generated by Django 5.2.7 on 2025-11-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0003_alter_wave_echo_alter_wave_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wave',
            options={'ordering': ['-created_at']},
        ),
    ]
