# Generated by Django 5.2.7 on 2025-11-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/noavatar.png', null=True, upload_to='avatars'),
        ),
    ]
