# Generated by Django 5.2.7 on 2025-11-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0003_alter_echo_updated_at_alter_echo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echo',
            options={'ordering': ['-created_at']},
        ),
    ]
